# Generated by Django 3.1.7 on 2021-03-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(db_column='系列', max_length=100, verbose_name='系列')),
                ('mark', models.CharField(db_column='牌号', max_length=100, verbose_name='牌号')),
                ('manufacturer', models.CharField(db_column='制造商', max_length=50, verbose_name='制造商')),
                ('link', models.CharField(db_column='链接', max_length=100, verbose_name='链接')),
                ('acronym', models.CharField(db_column='材料名称缩写', max_length=20, verbose_name='材料名称缩写')),
                ('material_type', models.CharField(db_column='材料类型', max_length=100, verbose_name='材料类型')),
                ('data_source', models.CharField(db_column='数据来源', max_length=100, verbose_name='数据来源')),
                ('last_modified_date', models.CharField(db_column='上次修改日期', max_length=50, verbose_name='上次修改日期')),
                ('test_date', models.CharField(db_column='测试日期', max_length=50, verbose_name='测试日期')),
                ('data_status', models.CharField(db_column='数据状态', max_length=50, verbose_name='数据状态')),
                ('material_id', models.CharField(db_column='材料ID', max_length=20, verbose_name='材料ID')),
                ('level_code', models.CharField(db_column='等级代码', max_length=50, verbose_name='等级代码')),
                ('vendor_code', models.CharField(db_column='供应商代码', max_length=50, verbose_name='供应商代码')),
                ('fibre_or_infill', models.CharField(db_column='纤维/填充物', max_length=100, verbose_name='纤维/填充物')),
            ],
        ),
    ]
