# Generated by Django 3.1.7 on 2021-03-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='c2',
            field=models.FloatField(db_column='c2', null=True, verbose_name='c2'),
        ),
    ]
