# Generated by Django 3.1.7 on 2021-03-09 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_material_c2'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='material',
            table='热塑性材料信息',
        ),
    ]
