# Generated by Django 3.1.7 on 2021-03-09 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210310_0033'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='material',
            table='test',
        ),
    ]
