# Generated by Django 3.1.7 on 2021-03-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210310_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='MFR_loading',
            field=models.FloatField(blank=True, db_column='MFR载入', null=True, verbose_name='MFR载入'),
        ),
        migrations.AddField(
            model_name='material',
            name='MFR_temperature',
            field=models.FloatField(blank=True, db_column='MFR温度', null=True, verbose_name='MFR温度'),
        ),
        migrations.AddField(
            model_name='material',
            name='absolute_maximum_melt_temperature',
            field=models.FloatField(blank=True, db_column='绝对最大溶体温度', null=True, verbose_name='绝对最大溶体温度'),
        ),
        migrations.AddField(
            model_name='material',
            name='c1',
            field=models.FloatField(blank=True, db_column='c1', null=True, verbose_name='c2'),
        ),
        migrations.AddField(
            model_name='material',
            name='conversion_temperature',
            field=models.FloatField(blank=True, db_column='转换温度', null=True, verbose_name='转换温度'),
        ),
        migrations.AddField(
            model_name='material',
            name='ejection_temperature',
            field=models.FloatField(blank=True, db_column='顶出温度', null=True, verbose_name='顶出温度'),
        ),
        migrations.AddField(
            model_name='material',
            name='elastic_modulus_e1',
            field=models.FloatField(blank=True, db_column='弹性模量E1', null=True, verbose_name='弹性模量E1'),
        ),
        migrations.AddField(
            model_name='material',
            name='elastic_modulus_e2',
            field=models.FloatField(blank=True, db_column='弹性模量E2', null=True, verbose_name='弹性模量E2'),
        ),
        migrations.AddField(
            model_name='material',
            name='maximum_shear_rate',
            field=models.FloatField(blank=True, db_column='最大剪切速率', null=True, verbose_name='最大剪切速率'),
        ),
        migrations.AddField(
            model_name='material',
            name='maximum_shear_stress',
            field=models.FloatField(blank=True, db_column='最大剪切应力', null=True, verbose_name='最大剪切应力'),
        ),
        migrations.AddField(
            model_name='material',
            name='measured_MFR',
            field=models.FloatField(blank=True, db_column='测量的MFR', null=True, verbose_name='测量的MFR'),
        ),
        migrations.AddField(
            model_name='material',
            name='melt_density',
            field=models.FloatField(blank=True, db_column='熔体密度', null=True, verbose_name='熔体密度'),
        ),
        migrations.AddField(
            model_name='material',
            name='melt_temperature',
            field=models.FloatField(blank=True, db_column='熔体温度', null=True, verbose_name='熔体温度'),
        ),
        migrations.AddField(
            model_name='material',
            name='melt_temperature_range_max',
            field=models.FloatField(blank=True, db_column='熔体温度范围（最大值）', null=True, verbose_name='熔体温度范围（最大值）'),
        ),
        migrations.AddField(
            model_name='material',
            name='melt_temperature_range_min',
            field=models.FloatField(blank=True, db_column='熔体温度范围（最小值）', null=True, verbose_name='熔体温度范围（最小值）'),
        ),
        migrations.AddField(
            model_name='material',
            name='model_surface_temperature',
            field=models.FloatField(blank=True, db_column='模具表面温度', null=True, verbose_name='模具表面温度'),
        ),
        migrations.AddField(
            model_name='material',
            name='mold_temperature_range_max',
            field=models.FloatField(blank=True, db_column='模具温度范围（最大值）', null=True, verbose_name='模具温度范围（最大值）'),
        ),
        migrations.AddField(
            model_name='material',
            name='mold_temperature_range_min',
            field=models.FloatField(blank=True, db_column='模具温度范围（最小值）', null=True, verbose_name='模具温度范围（最小值）'),
        ),
        migrations.AddField(
            model_name='material',
            name='poisson_ratio_v12',
            field=models.FloatField(blank=True, db_column='泊松比v12', null=True, verbose_name='泊松比v12'),
        ),
        migrations.AddField(
            model_name='material',
            name='poisson_ratio_v23',
            field=models.FloatField(blank=True, db_column='泊松比v23', null=True, verbose_name='泊松比v23'),
        ),
        migrations.AddField(
            model_name='material',
            name='pvt_b1m',
            field=models.FloatField(blank=True, db_column='pvt-b1m', null=True, verbose_name='pvt-b1m'),
        ),
        migrations.AddField(
            model_name='material',
            name='pvt_b1s',
            field=models.FloatField(blank=True, db_column='pvt-b1s', null=True, verbose_name='pvt-b1s'),
        ),
        migrations.AddField(
            model_name='material',
            name='pvt_b2m',
            field=models.FloatField(blank=True, db_column='pvt-b2m', null=True, verbose_name='pvt-b2m'),
        ),
        migrations.AddField(
            model_name='material',
            name='pvt_b2s',
            field=models.FloatField(blank=True, db_column='pvt-b2s', null=True, verbose_name='pvt-b2s'),
        ),
        migrations.AddField(
            model_name='material',
            name='pvt_b3m',
            field=models.FloatField(blank=True, db_column='pvt-b3m', null=True, verbose_name='pvt-b3m'),
        ),
        migrations.AddField(
            model_name='material',
            name='pvt_b3s',
            field=models.FloatField(blank=True, db_column='pvt-b3s', null=True, verbose_name='pvt-b3s'),
        ),
        migrations.AddField(
            model_name='material',
            name='pvt_b4m',
            field=models.FloatField(blank=True, db_column='pvt-b4m', null=True, verbose_name='pvt-b4m'),
        ),
        migrations.AddField(
            model_name='material',
            name='pvt_b4s',
            field=models.FloatField(blank=True, db_column='pvt-b4s', null=True, verbose_name='pvt-b4s'),
        ),
        migrations.AddField(
            model_name='material',
            name='pvt_b5',
            field=models.FloatField(blank=True, db_column='pvt-b5', null=True, verbose_name='pvt-b5'),
        ),
        migrations.AddField(
            model_name='material',
            name='pvt_b6',
            field=models.FloatField(blank=True, db_column='pvt-b6', null=True, verbose_name='pvt-b6'),
        ),
        migrations.AddField(
            model_name='material',
            name='pvt_b7',
            field=models.FloatField(blank=True, db_column='pvt-b7', null=True, verbose_name='pvt-b7'),
        ),
        migrations.AddField(
            model_name='material',
            name='pvt_b8',
            field=models.FloatField(blank=True, db_column='pvt-b8', null=True, verbose_name='pvt-b8'),
        ),
        migrations.AddField(
            model_name='material',
            name='pvt_b9',
            field=models.FloatField(blank=True, db_column='pvt-b9', null=True, verbose_name='pvt-b9'),
        ),
        migrations.AddField(
            model_name='material',
            name='seven_params_A1',
            field=models.FloatField(blank=True, db_column='七参数A1', null=True, verbose_name='七参数A1'),
        ),
        migrations.AddField(
            model_name='material',
            name='seven_params_A2',
            field=models.FloatField(blank=True, db_column='七参数A2', null=True, verbose_name='七参数A2'),
        ),
        migrations.AddField(
            model_name='material',
            name='seven_params_D1',
            field=models.FloatField(blank=True, db_column='七参数D1', null=True, verbose_name='七参数D1'),
        ),
        migrations.AddField(
            model_name='material',
            name='seven_params_D2',
            field=models.FloatField(blank=True, db_column='七参数D2·', null=True, verbose_name='七参数D2·'),
        ),
        migrations.AddField(
            model_name='material',
            name='seven_params_D3',
            field=models.FloatField(blank=True, db_column='七参数D3', null=True, verbose_name='七参数D3'),
        ),
        migrations.AddField(
            model_name='material',
            name='seven_params_Tau',
            field=models.FloatField(blank=True, db_column='七参数Tau*', null=True, verbose_name='七参数Tau*'),
        ),
        migrations.AddField(
            model_name='material',
            name='seven_params_n',
            field=models.FloatField(blank=True, db_column='七参数n', null=True, verbose_name='七参数n'),
        ),
        migrations.AddField(
            model_name='material',
            name='shear_modulus_g12',
            field=models.FloatField(blank=True, db_column='剪切模量G12', null=True, verbose_name='剪切模量G12'),
        ),
        migrations.AddField(
            model_name='material',
            name='solid_density',
            field=models.FloatField(blank=True, db_column='固体密度', null=True, verbose_name='固体密度'),
        ),
        migrations.AddField(
            model_name='material',
            name='thermal_expansion_data_transverse_isotropic_coefficient_alpha1',
            field=models.FloatField(blank=True, db_column='热膨胀数据横向各向同性系数alpha1', null=True, verbose_name='热膨胀数据横向各向同性系数alpha1'),
        ),
        migrations.AddField(
            model_name='material',
            name='thermal_expansion_data_transverse_isotropic_coefficient_alpha2',
            field=models.FloatField(blank=True, db_column='热膨胀数据横向各向同性系数alpha2', null=True, verbose_name='热膨胀数据横向各向同性系数alpha2'),
        ),
        migrations.AlterField(
            model_name='material',
            name='c2',
            field=models.FloatField(blank=True, db_column='c2', null=True, verbose_name='c2'),
        ),
        migrations.AlterModelTable(
            name='material',
            table=None,
        ),
    ]
