# Generated by Django 3.1.7 on 2021-03-10 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210310_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'managed': False},
        ),
    ]
