# Generated by Django 3.1.7 on 2021-03-10 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210310_1140'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='material',
            table='test',
        ),
    ]
